function build_task5()
% Task 5: нелинейный логический регулятор. Реализация:
% — три Transfer Fcn-блока для динамических ветвей
% — MATLAB Function-блок реализующий логику переключения и зоны нечувствительности

mdl = 'task5_model';
close_system(mdl, 0);
new_system(mdl);
open_system(mdl);

num_W = [1181700000 24464220000 16604400000];
den_W = [3 9090062 187860040 23755200000 16604400000];

add_block('simulink/Sources/Step', [mdl '/Step'], ...
    'Time','0','Before','0','After','100', 'Position','[20 130 50 160]');
add_block('simulink/Math Operations/Sum', [mdl '/Sum'], ...
    'Inputs','+-','Position','[80 130 110 160]');

% Lead-фильтры
add_block('simulink/Continuous/Transfer Fcn', [mdl '/Lead5'], ...
    'Numerator','[2 1]','Denominator','[5 1]', 'Position','[150 30 220 70]');
add_block('simulink/Continuous/Transfer Fcn', [mdl '/Lead3'], ...
    'Numerator','[2 1]','Denominator','[3 1]', 'Position','[150 90 220 130]');
add_block('simulink/Continuous/Transfer Fcn', [mdl '/H18'], ...
    'Numerator','[18]','Denominator','[0.05 1]', 'Position','[250 30 320 70]');

% MATLAB Function блок с логикой
add_block('simulink/User-Defined Functions/MATLAB Function', [mdl '/NLReg'], ...
    'Position','[360 70 470 200]');
% Тело функции записывается через Stateflow API
root = sfroot();
chart = root.find('-isa','Stateflow.EMChart','Path',[mdl '/NLReg']);
chart.Script = sprintf([ ...
'function F = nlreg(e, lead5, lead3, h18)\n' ...
'    delta = 1;\n' ...
'    k = 1;\n' ...
'    if e > 10\n' ...
'        g1 = lead5;\n' ...
'    else\n' ...
'        g1 = lead3;\n' ...
'    end\n' ...
'    if abs(g1) > 7\n' ...
'        z = h18;\n' ...
'    else\n' ...
'        z = 5*lead3;\n' ...
'    end\n' ...
'    if abs(z) <= delta\n' ...
'        F = 0;\n' ...
'    else\n' ...
'        F = k*z - delta*sign(z);\n' ...
'    end\n' ...
'end\n']);

% Объект
add_block('simulink/Continuous/Transfer Fcn', [mdl '/W'], ...
    'Numerator', mat2str(num_W), 'Denominator', mat2str(den_W), ...
    'Position','[510 110 620 160]');
add_block('simulink/Sinks/Scope', [mdl '/Scope_y'], 'Position','[660 110 690 150]');
add_block('simulink/Sinks/Scope', [mdl '/Scope_F'], 'Position','[510 200 540 240]');

add_line(mdl, 'Step/1','Sum/1');
add_line(mdl, 'Sum/1','Lead5/1','autorouting','on');
add_line(mdl, 'Sum/1','Lead3/1','autorouting','on');
add_line(mdl, 'Sum/1','NLReg/1','autorouting','on');
add_line(mdl, 'Lead5/1','H18/1');
add_line(mdl, 'Lead5/1','NLReg/2','autorouting','on');
add_line(mdl, 'Lead3/1','NLReg/3','autorouting','on');
add_line(mdl, 'H18/1','NLReg/4','autorouting','on');
add_line(mdl, 'NLReg/1','W/1','autorouting','on');
add_line(mdl, 'NLReg/1','Scope_F/1','autorouting','on');
add_line(mdl, 'W/1','Scope_y/1');
add_line(mdl, 'W/1','Sum/2','autorouting','on');

set_param(mdl, 'StopTime','30');
save_system(mdl);
fprintf('Сохранено: %s.slx\n', mdl);
end
