function build_task7()
% Simulink-модель task7_aim2.slx — АИМ-2 на MATLAB Function

mdl = 'task7_aim2';
close_system(mdl, 0);
new_system(mdl);
open_system(mdl);

add_block('simulink/Sources/Sine Wave', [mdl '/Sine'], ...
    'Amplitude','1','Frequency','2*pi*0.3','Position','[20 80 50 110]');
add_block('simulink/Sources/Clock', [mdl '/Clock'], ...
    'Position','[20 130 50 160]');
add_block('simulink/User-Defined Functions/MATLAB Function', [mdl '/AIM2'], ...
    'Position','[90 80 170 150]');
add_block('simulink/Sinks/Scope', [mdl '/Scope'], 'Position','[210 80 240 110]');

% Записываем тело MATLAB Function
root = sfroot();
fcn = root.find('-isa','Stateflow.EMChart','Path',[mdl '/AIM2']);
if ~isempty(fcn)
    fcn.Script = sprintf([ ...
'function y = aim2(u, t)\n' ...
'    T = 1.0;\n' ...
'    gamma = 0.6;\n' ...
'    phase = mod(t, T);\n' ...
'    if phase < gamma*T\n' ...
'        y = u;\n' ...
'    else\n' ...
'        y = 0;\n' ...
'    end\n' ...
'end\n']);
end

add_line(mdl, 'Sine/1','AIM2/1');
add_line(mdl, 'Clock/1','AIM2/2');
add_line(mdl, 'AIM2/1','Scope/1');

set_param(mdl, 'StopTime','10');
save_system(mdl);
fprintf('Сохранено: %s.slx\n', mdl);
end
